image: condaforge/mambaforge:4.12.0-0

# TODO this is run before every test and the '--force' flag is needed because
# the env is apparently cached (soooooo need to figure out how to figure out
# if conda env is installed or not)
before_script:
  - ls -al /
  - mount
  - mamba env create -f env.yml
  - conda activate snakemake-ebm

snakemake_dry:
  stage: test
  script:
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --dryrun

# snakemake_chr21:
#   stage: test
#   script:
#     - >
#       snakemake -p --use-conda --cores 4 --verbose
#       --configfile config/dynamic-testing.yml
