image: condaforge/mambaforge:4.12.0-0

before_script:
  - mamba env create -f env.yml
  - conda activate snakemake-ebm

snakemake_dry:
  script:
    - snakemake -p --use-conda --cores 1 --verbose --dryrun
