# image: condaforge/mambaforge:4.12.0-0

variables:
  ENV_DIR: ./this-env

stages:
  - snakemake_global
  - snakemake_conda
  - test

# - ASSUME mamba is already installed on the system hosting the gitlab runner
# - ASSUME the cache will track any changes to env.yml and will force an update
#   if this changes
install_env:
  stage: snakemake_global
  script:
    - >
      test -d $ENV_DIR
      && echo "Env already created"
      || mamba env create -f env.yml -p $ENV_DIR
  cache:
    policy: pull-push
    paths:
      - $ENV_DIR
    key:
      files:
        - env.yml

install_smk_conda_envs:
  stage: snakemake_conda
  script:
    - conda activate $ENV_DIR
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --conda-create-envs-only
  cache:
    - policy: pull
      paths:
        - this-env
      key:
        files:
          - env.yml
    - policy: pull-push
      paths:
        - .snakemake/conda
      key:
        files:
          - workflow/envs

snakemake_dry:
  stage: test
  script:
    - conda activate $ENV_DIR
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --dryrun
  cache:
    policy: pull
    paths:
      - this-env
    key:
      files:
        - env.yml

snakemake_chr21:
  stage: test
  script:
    - conda activate $ENV_DIR
    - >
      snakemake -p --use-conda --cores 1 --verbose
      --configfile config/dynamic-testing.yml
  cache:
    - policy: pull
      paths:
        - this-env
      key:
        files:
          - env.yml
    - policy: pull
      paths:
        - .snakemake/conda
      key:
        files:
          - workflow/envs
