image: condaforge/mambaforge:4.12.0-0

before_script:
  - mamba env create -f env.yml --force
  - conda activate snakemake-ebm

snakemake_dry:
  stage: test
  script:
    - >
      snakemake -p --use-conda --cores 1 --verbose
      --configfile config/dynamic-testing.yml
      --dryrun
