# image: condaforge/mambaforge:4.12.0-0

stages:
  - build
  - test

# NOTE this assumes mamba is already installed on the system hosting the gitlab
# runner
install_env:
  stage: build
  script:
    - mamba env create -f env.yml -p ./this-env
  cache:
    policy: pull-push
    paths:
      - this-env
    key:
      files:
        - env.yml

install_smk_conda_envs:
  needs: [install_env]
  stage: build
  script:
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --conda-create-envs-only
  cache:
    policy: pull-push
    paths:
      - .snakemake/conda
    key:
      files:
        - workflow/envs

snakemake_dry:
  stage: test
  script:
    - conda activate ./this-env
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --dryrun
  cache:
    policy: pull
    paths:
      - this-env
    key:
      files:
        - env.yml

snakemake_chr21:
  stage: test
  script:
    - >
      snakemake -p --use-conda --cores 4 --verbose
      --configfile config/dynamic-testing.yml
  cache:
    - policy: pull
      paths:
        - this-env
      key:
        files:
          - env.yml
    - policy: pull
      paths:
        - .snakemake/conda
      key:
        files:
          - workflow/envs
