# image: condaforge/mambaforge:4.12.0-0

stages:
  - snakemake_global
  - snakemake_conda
  - test

# NOTE this assumes mamba is already installed on the system hosting the gitlab
# runner
install_env:
  stage: snakemake_global
  script:
    - >
      if conda env list | grep "snakemake-ebm" >/dev/null 2>&1; then
      echo "Env already created"
      else
      mamba env create -f env.yml -p ./this-env
      fi
  cache:
    policy: pull-push
    paths:
      - this-env
    key:
      files:
        - env.yml

install_smk_conda_envs:
  stage: snakemake_conda
  script:
    - conda activate ./this-env
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --conda-create-envs-only
  cache:
    policy: pull-push
    paths:
      - .snakemake/conda
    key:
      files:
        - workflow/envs

snakemake_dry:
  stage: test
  script:
    - conda activate ./this-env
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --dryrun
  cache:
    policy: pull
    paths:
      - this-env
    key:
      files:
        - env.yml

snakemake_chr21:
  stage: test
  script:
    - conda activate ./this-env
    - >
      snakemake -p --use-conda --cores 1 --verbose
      --configfile config/dynamic-testing.yml
  cache:
    - policy: pull
      paths:
        - this-env
      key:
        files:
          - env.yml
    - policy: pull
      paths:
        - .snakemake/conda
      key:
        files:
          - workflow/envs
