# image: condaforge/mambaforge:4.12.0-0

stages:
  - build
  - test

# NOTE this assumes mamba is already installed on the system hosting the gitlab
# runner
install_env:
  stage: build
  script:
    - mamba env create -f env.yml -p ./this-env
  cache:
    paths:
      - this-env
    - key:
        files:
          - env.yml

snakemake_dry:
  stage: test
  script:
    - conda activate ./this-env
    - >
      snakemake --use-conda --cores 1
      --configfile config/dynamic-testing.yml
      --dryrun
  cache:
    paths:
      - this-env
    - key:
        files:
          - env.yml

# snakemake_chr21:
#   stage: test
#   script:
#     - >
#       snakemake -p --use-conda --cores 4 --verbose
#       --configfile config/dynamic-testing.yml
