stages:
  snakemake:
    cmd: snakemake -p --verbose -r -j 1 --use-conda --cores 1
    deps:
    - config/dynamic.yml
    outs:
    - results/annotated_input:
        persist: true
    - results/ebm:
        persist: true
