stages:
  snakemake:
    cmd: snakemake --configfile=config/dynamic.yml --profile workflow/profiles/local
    deps:
    - config/dynamic.yml
    outs:
    - results/annotated_input:
        persist: true
    - results/ebm:
        persist: true
