# directories for input/output files
paths:
  resources: "resources"
  results: "results"

# TODO this isn't being used yet
# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  HG002-DV:
    # TODO add option to either verify the input with an MD5 or use a url
    vcf: HG002.hiseqx.pcr-free.40x.dedup.grch38_chr1_22.vcf
    ref: GRCh38
    benchmark: v4.2.1

# paths/urls for files to be downloaded for processing the inputs
resources:
  benchmarks:
    v4.2.1:
      vcf_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
      tbi_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi
      bed_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
  references:
    GRCh38:
      sdf: https://s3.amazonaws.com/rtg-datasets/references/GRCh38.sdf.zip
  annotations:
    mappability:
      low: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l100_m2_e1.bed.gz
      high: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz

# settings for each EBM run
ebm_settings:
  ebm_test:
    # hyperparameters:
    test_size: 0.2

# different feature sets for each EBM run and annotation
feature_sets:
  all_features:
    indel_length:
    period_min:
    copyNum_max:
    perMatch_median:
    region_length:
    SINE:
    LINE:
    LTR:
    Satellite:

  trans_features:
    indel_length:
      log_transform: true
    period_min:
      log_transform: true
    copyNum_max:
      log_transform: true
    perMatch_median:
      log_transform: true
    region_length:
      log_transform: true
    SINE:
      log_transform: true
    LINE:
      log_transform: true
    LTR:
      log_transform: true
    Satellite:
      log_transform: true

# settings for each ebm run
ebm_runs:
  test_v1:
    input: HG002-DV
    filter: INDEL
    feature_set: trans_features
    ebm_settings: ebm_test
  other_v1:
    input: HG002-DV
    filter: SNP
    feature_set: all_features
    ebm_settings: ebm_test
