# directories for input/output files
paths:
  resources: "resources"
  results: "results"

# TODO this isn't being used yet
# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  HG002-DV:
    # TODO add option to either verify the input with an MD5 or use a url
    vcf: HG002.hiseqx.pcr-free.40x.dedup.grch38_chr1_22.vcf
    ref: GRCh38
    benchmark: v4.2.1

# paths/urls for files to be downloaded for processing the inputs
resources:
  benchmarks:
    v4.2.1:
      vcf_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
      tbi_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi
      bed_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
  references:
    GRCh38:
      sdf: https://s3.amazonaws.com/rtg-datasets/references/GRCh38.sdf.zip
  annotations:
    mappability:
      low: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l100_m2_e1.bed.gz
      high: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz
    superdups: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
    homopolymers:
      find_regions: https://opendata.nist.gov/pdrsrv/mds2-2190/GRCh38/LowComplexity/findSimpleRegions_quad.py
      fasta: https://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
      

# settings for each EBM run
ebm_settings:
  ebm_test:
    # hyperparameters:
    test_size: 0.2

# different feature sets for each EBM run and annotation
feature_sets:
  all_indel_features:
    # VCF
    DP:
    VAF:
    indel_length:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:
    # tandem repeats
    period_min:
    copyNum_max:
    perMatch_median:
    region_length:
    # repeat masker
    SINE:
    LINE:
    LTR:
    Satellite:
    # mappability
    mappability_high:
    mappability_low:

  all_snp_features:
    # VCF
    DP:
    VAF:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:
    # tandem repeats
    period_min:
    copyNum_max:
    perMatch_median:
    region_length:
    # repeat masker
    SINE:
    LINE:
    LTR:
    Satellite:
    # mappability
    mappability_high:
    mappability_low:

  prev_indel_features:
    # VCF
    DP:
    VAF:
    indel_length:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:

  prev_snp_features:
    # VCF
    DP:
    VAF:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:

# settings for each ebm run
ebm_runs:
  all_snp_v1:
    input: HG002-DV
    filter: SNP
    feature_set: all_snp_features
    ebm_settings: ebm_test
  all_indel_v1:
    input: HG002-DV
    filter: INDEL
    feature_set: all_indel_features
    ebm_settings: ebm_test
  prev_snp_v1:
    input: HG002-DV
    filter: SNP
    feature_set: prev_snp_features
    ebm_settings: ebm_test
  prev_indel_v1:
    input: HG002-DV
    filter: INDEL
    feature_set: prev_indel_features
    ebm_settings: ebm_test
