# TODO this isn't being used yet
# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  HG002-DV:
    # TODO add option to either verify the input with an MD5 or use a url
    vcf: HG002.hiseqx.pcr-free.40x.dedup.grch38_chr1_22.vcf
    ref: GRCh38
    benchmark: v4.2.1

# settings for each EBM run
ebm_settings:
  ebm_test:
    # hyperparameters:
    test_size: 0.2

# different feature sets for each EBM run and annotation
feature_sets:
  all_indel_features:
    # VCF
    DP:
    VAF:
    indel_length:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:
    # tandem repeats
    period_min:
    copyNum_max:
    perMatch_median:
    region_length:
    # repeat masker
    SINE:
    LINE:
    LTR:
    Satellite:
    # mappability
    mappability_high:
    mappability_low:

  all_snp_features:
    # VCF
    DP:
    VAF:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:
    # tandem repeats
    period_min:
    copyNum_max:
    perMatch_median:
    region_length:
    # repeat masker
    SINE:
    LINE:
    LTR:
    Satellite:
    # mappability
    mappability_high:
    mappability_low:

  prev_indel_features:
    # VCF
    DP:
    VAF:
    indel_length:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:

  prev_snp_features:
    # VCF
    DP:
    VAF:
    # segdups
    alignL_max:
    fracMatchIndel_max:
    alignL_count:
    # homopolymers
    AT_homopolymer_length:
    GC_homopolymer_length:

# settings for each ebm run
ebm_runs:
  all_snp_v1:
    input: HG002-DV
    filter: SNP
    feature_set: all_snp_features
    ebm_settings: ebm_test
  all_indel_v1:
    input: HG002-DV
    filter: INDEL
    feature_set: all_indel_features
    ebm_settings: ebm_test
  prev_snp_v1:
    input: HG002-DV
    filter: SNP
    feature_set: prev_snp_features
    ebm_settings: ebm_test
  prev_indel_v1:
    input: HG002-DV
    filter: INDEL
    feature_set: prev_indel_features
    ebm_settings: ebm_test
