$schema: "http://json-schema.org/draft-07/schema#"
description: explainable boosted machines pipeline
required:
  - resources
  - global
  - runs
additionalProperties: false
properties:

################################################################################
# resources

  resources:
    additionalProperties: false
    required:
      - query_url
      - bench
      - ref
    properties:
      query_url:
        description: the url for the query VCF to use
        type: string
        format: uri

      bench:
        additionalProperties: false
        required:
          - vcf_url
          - bed_url
        properties:
          vcf_url:
            description: the url for the benchmark VCF to use
            type: string
            format: uri
          bed_url:
            description: the url for the benchmark bed to use
            type: string
            format: uri

      ref:
        additionalProperties: false
        required:
          - sdf_url
        sdf:
          description: the url for the reference SDF to use
          type: string
          format: uri

################################################################################
# global

  global:
    anyOf:
      $ref: "$defs/run_config"

################################################################################
# runs

  runs:
    patternProperties:
      ^[A-Za-z0-9_]+_v[0-9]+$:
        anyOf:
          $ref: "$defs/run_config"

################################################################################
# common

  $defs:
    run_config:
      additionalProperties: false
      required:
        - features
        - ebm
        properties:
          features:
            additionalProperties: false
            patternProperties:
              ^[A-Za-z0-9_]+$:
                additionalProperties: false
                properties:
                  log_transform:
                    description: log transform the feature if 'true'
                    type: boolean
                  fill_na:
                    description: if present, fill missing values with this value
                    type: float

          ebm:
            additionalProperties: false
            required:
              - test_size
            properties:
              test_size:
                description: |
                  the size of the testing partition when training the model
                type: float
                minimum: 0
                maximum: 1
                      
                  
