# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  # TODO add option to either verify the input with an MD5 or use a url
  HG002_Illumina_DV:
    vcf: illumina-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
    chr_filter: [chr21]
  HG002_Hifi_DV:
    vcf: hifi-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
    chr_filter: [chr21]

# settings for each ebm run
ebm_runs:
  small_set_v3:
    inputs:
      # - [HG002_Illumina_DV]
      # - [HG002_Hifi_DV]
      - [HG002_Illumina_DV, HG002_Hifi_DV]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    error_labels: [fp]
    include_filtered: false
    interactions:
      - VCF_input
    features: &base_features
      VCF_input:
        feature_type: categorical
      VCF_VAF: {}
      VCF_DP: {}
      VCF_indel_length: {}

      HOMOPOL_AT_length: {}
      HOMOPOL_GC_length: {}
      HOMOPOL_AT_imperfect_frac: {}
      HOMOPOL_GC_imperfect_frac: {}
      HOMOPOL_AT_total_imperfect_frac: {}
      HOMOPOL_GC_total_imperfect_frac: {}

      TR_unit_size_max: {}
      TR_unit_copies_max: {}
      TR_identity_min: {}
      TR_score_max: {}
      TR_percent_AT_median:
        fill_na: -1

      REPMASK_SINE_length: {}
      REPMASK_LINE_length: {}

      # mappability
      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      # segdups
      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count: {}
