inputs:
  HG002_Illumina_DV:
    # manually restrict to not X/Y because clinvar has X/Y and the benchmarks
    # don't, and currently the model will try to run any chromosomes it can find
    # if I don't use a filter
    chr_filter: &filter [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
    train:
      url: https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch38/vcf/hiseqx/wgs_pcr_free/40x/HG002.hiseqx.pcr-free.40x.deepvariant-v1.0.grch38.vcf.gz
      ref: GRCh38
      benchmark: HG002_v4.2.1
    test:
      HG005_Illumina_DV:
        url: https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch38/vcf/hiseqx/wgs_pcr_free/40x/HG005.hiseqx.pcr-free.40x.deepvariant-v1.0.grch38.vcf.gz
        ref: GRCh38
        benchmark: HG005_v4.2.1
      # Clinvar_Illumina: &clinvar
      #   url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2022/clinvar_20220812.vcf.gz
      #   ref: GRCh38
      #   # isn't genomics wonderful?
      #   chr_prefix: ''
      #   format_fields: {}
      #   benchmark: null
      #   # There are some super long variants in clinvar. Filter these out
      #   # because a) they would overlap with so many annotations that a new
      #   # universe would spawn into existance and b) they are outside what a
      #   # trained model would be good at testing anyways (until we incorporate
      #   # structural variants)
      #   max_ref: 50
      #   max_alt: 50
      #   format_fields:
      #     vaf: null
      #     dp: null
      #     gt: null
      #     gq: null
  HG002_Ultima_DV:
    chr_filter: *filter
    train:
      url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG002_005401-UGAv3-1-CACATCCTGCATGTGAT.vcf.gz
      ref: GRCh38
      benchmark: HG002_v4.2.1
    test:
      HG005_Ultima_DV:
        url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG005_004731-UGAv3-32-CATCTGGTGCATGTGAT.vcf.gz
        ref: GRCh38
        benchmark: HG005_v4.2.1
      # Clinvar_Hifi: *clinvar

ebm_runs:
  vcf_interaction_fn_v1:
    inputs: &ebm_inputs
      - HG002_Ultima_DV: [HG005_Ultima_DV]
        HG002_Illumina_DV: [HG005_Illumina_DV]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    error_labels: [fn]
    filtered_are_candidates: false
    interactions:
      - VCF_input

    features: &base_features
      VCF_input:
        feature_type: categorical
      VCF_indel_length:
        visualization:
          plot_type: bar
          truncate: {lower: -50, upper: 50}

      HOMOPOL_AT_length:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_GC_length:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_AT_total_imperfect_frac:
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_GC_total_imperfect_frac:
        fill_na: -1
        visualization:
          split_missing: 0

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0
      TR_length:
        transform: log
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean:
        visualization:
          split_missing: 0.85
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}

  vcf_interaction_combined_v1:
    inputs: *ebm_inputs
    filter: [SNP, INDEL]
    ebm_settings:
      <<: *ebm_settings
    error_labels: [fn, fp]
    interactions:
      - VCF_input
    filtered_are_candidates: false
    features:
      <<: *base_features
