# TODO this isn't being used yet
# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  # TODO add option to either verify the input with an MD5 or use a url
  # vcf: HG002.hiseqx.pcr-free.40x.dedup.grch38_chr1_22.vcf
  HG002_Illumina_DV:
    vcf: illumina-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
  HG002_Hifi_DV:
    vcf: hifi-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1

# settings for each ebm run
ebm_runs:
  no_DP_VAF_v1:
    inputs: [HG002_Illumina_DV, HG002_Hifi_DV]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    features: &base_features
      # segdups
      alignL_max:
        fill_na: -1
      fracMatchIndel_max:
        fill_na: -1
      alignL_count:
        fill_na: -1
      # homopolymers
      AT_homopolymer_length:
        fill_na: -1
      GC_homopolymer_length:
        fill_na: -1
      period_min:
        fill_na: -1
      copyNum_max:
        fill_na: -1
      perMatch_median:
        fill_na: -1
      region_length:
        fill_na: -1
      # repeat masker
      SINE:
        fill_na: -1
      LINE:
        fill_na: -1
      LTR:
        fill_na: -1
      Satellite:
        fill_na: -1
      # mappability
      mappability_high:
        feature_type: categorical
      mappability_low:
        feature_type: categorical

  all_v1:
    inputs: [HG002_Illumina_DV, HG002_Hifi_DV]
    filter: [INDEL, SNP]
    ebm_settings: *ebm_settings
    features: &all_features
      <<: *base_features
      DP: {}
      VAF: {}
