# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  # TODO add option to either verify the input with an MD5 or use a url
  HG002_Illumina_DV:
    vcf: illumina-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
    chr_filter: [chr21]
  HG002_Hifi_DV:
    vcf: hifi-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
    chr_filter: [chr21]

# settings for each ebm run
ebm_runs:
  small_set_v3:
    inputs:
      # - [HG002_Illumina_DV]
      # - [HG002_Hifi_DV]
      - [HG002_Illumina_DV, HG002_Hifi_DV]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    error_labels: [fp]
    include_filtered: false
    interactions:
      - input
    features: &base_features
      # input file
      input:
        feature_type: categorical
      # core
      VAF: {}
      DP: {}
      indel_length: {}
      # homopolymers
      AT_homopolymer_length: {}
      GC_homopolymer_length: {}
      AT_homopolymer_perfect_frac: {}
      GC_homopolymer_perfect_frac: {}
      # tandem repeats
      period_max: {}
      copyNum_max: {}
      perMatch_min: {}
      score_max: {}
      AT_median:
        fill_na: -1
      # repeat masker
      SINE: {}
      LINE: {}
      # mappability
      mappability_high:
        feature_type: categorical
      mappability_low:
        feature_type: categorical
      # segdups
      alignL_max: {}
      fracMatchIndel_mean: {}
      fracMatchIndel_count: {}
