inputs:
  HG002_Illumina_DV:
    url: null
    ref: GRCh38
    benchmark: draft_v2.7_xy
    chr_filter: [chrX, chrY]
  HG002_Hifi_DV:
    url: https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/PacBio_CCS_15kb_20kb_chemistry2_10312019/GRCh38/deepvariant_HG002_GRCh38_15kb_37X_SequelII.vcf.gz
    ref: GRCh38
    benchmark: draft_v2.7_xy
    chr_filter: [chrX, chrY]

ebm_runs:
  xy_fn_v1:
    inputs:
      - [HG002_Hifi_DV, HG002_Illumina_DV]
    filter: [SNP, INDEL]
    error_labels: [fn]
    filtered_are_candidates: false
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    features: &base_features
      VCF_indel_length:
        visualization:
          truncate: {lower: -50, upper: 50}

      HOMOPOL_AT_length:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_GC_length:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_AT_total_imperfect_frac:
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_GC_total_imperfect_frac:
        fill_na: -1
        visualization:
          split_missing: 0

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_unit_copies_max:
        visualization:
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_score_max: {}
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}
