# the VCF file to annotate and analyze via EBMs and associated metadata
inputs:
  # TODO add option to either verify the input with an MD5 or use a url
  HG002_Illumina_DV:
    vcf: illumina-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1
  HG002_Hifi_DV:
    vcf: hifi-query.vcf.gz
    ref: GRCh38
    benchmark: v4.2.1

# settings for each ebm run
ebm_runs:
  fp_and_fn_v1: &base_settings
    inputs: [HG002_Illumina_DV, HG002_Hifi_DV]
    filter: [SNP, INDEL]
    ebm_settings:
      split_parameters:
        test_size: 0.2
    features:
      # core
      VAF: {}
      DP: {}
      indel_length: {}
      # homopolymers
      AT_homopolymer_length: {}
      GC_homopolymer_length: {}
      # tandem repeats
      period_max: {}
      copyNum_max: {}
      perMatch_min: {}
      score_max: {}
      AT_median:
        fill_na: -1
      # repeat masker
      SINE: {}
      LINE: {}
      # mappability
      mappability_high:
        feature_type: categorical
      mappability_low:
        feature_type: categorical
      # segdups
      alignL_max: {}
      fracMatchIndel_mean: {}
      fracMatchIndel_count: {}

  fp_only_v1:
    <<: *base_settings
    error_labels: [fp]

  fn_only_v1:
    <<: *base_settings
    error_labels: [fn]
