# directories for input/output files
paths:
  resources: "resources"
  results: "results"

# paths/urls for files to be downloaded for processing the inputs
resources:
  benchmarks:
    v4.2.1:
      vcf_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
      tbi_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi
      bed_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
    draft_v0.005:
      vcf_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/T2T-HG002-XY-v2.7/20220324_v0.005_HG002XYvsGRCh38/preliminary-draft-small-variant-benchmark-files/GRCh38_T2T-XY-v2.7_dipcall-z2k.vcf.gz
      tbi_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/T2T-HG002-XY-v2.7/20220324_v0.005_HG002XYvsGRCh38/preliminary-draft-small-variant-benchmark-files/GRCh38_T2T-XY-v2.7_dipcall-z2k.vcf.gz.tbi
      bed_url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/T2T-HG002-XY-v2.7/20220324_v0.005_HG002XYvsGRCh38/preliminary-draft-small-variant-benchmark-files/GRCh38_T2T-XY-v2.7_dipcall-z2k.excluded.bed
  references:
    GRCh38:
      sdf: https://s3.amazonaws.com/rtg-datasets/references/GRCh38.sdf.zip
      genome: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz
      annotations:
        mappability:
          low: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_lowmappabilityall.bed.gz
          high: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz
        superdups: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
        simreps: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
        repeat_masker: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz

# TODO some of these feature names might be reference-dependent
features:
  label: label

  index:
    chr: chrom
    start: chromStart
    end: chromEnd

  vcf:
    prefix: VCF
    columns:
      input: input
      qual: QUAL
      filter: FILTER
      gt: GT
      gq: GQ
      dp: DP
      ad: AD
      vaf: VAF
      len: indel_length

  mappability:
    prefix: MAP
    suffixes:
      low: difficult_100bp
      high: difficult_250bp

  homopolymers:
    prefix: HOMOPOL
    bases: [AT, GC]
    suffixes:
      len: length
      tot_imp_frac: total_imperfect_frac
      imp_frac: imperfect_frac
      imp_cnt: imperfect_count

  repeat_masker:
    prefix: REPMASK
    suffixes:
      len: length
    classes:
      SINE: []
      LINE: [L1, L2, CR1, RTE-X, RTE-BovB, Penelope, Dong-R4]
      LTR: []
      Satellite: []

  segdups:
    prefix: SEGDUP
    columns:
      alignL: size
      fracMatchIndel: identity
    operations: [min, max, mean]

  tandem_repeats:
    prefix: TR
    columns:
      period: unit_size
      copyNum: unit_copies
      perMatch: identity
      perIndel: per_indel_mismatch
      score: score
    bases_prefix: percent
    operations: [max, min, median]
    other:
      len: length
