$schema: "http://json-schema.org/draft-07/schema#"
description: explainable boosted machines pipeline
required:
  - paths
  - resources
  - global
  - runs
additionalProperties: false
properties:

################################################################################
# paths
  paths:
    additionalProperties: false
    required:
      - resources
      - results
    properties:
      resources:
        description: the path in which snakemake will put resource files
        type: string
      results:
        description: the path in which snakemake will put result files
        type: string

################################################################################
# resources

  resources:
    additionalProperties: false
    required:
      # - query_url
      - bench
      - ref
      - annotations
    properties:
      # query_url:
      #   description: the url for the query VCF to use
      #   type: string
      #   format: uri

      bench:
        additionalProperties: false
        required:
          - vcf_url
          - bed_url
        properties:
          vcf_url:
            description: the url for the benchmark VCF to use
            type: string
            format: uri
          tbi_url:
            description: the url for the benchmark VCF TBI to use
            type: string
            format: uri
          bed_url:
            description: the url for the benchmark bed to use
            type: string
            format: uri

      ref:
        additionalProperties: false
        required:
          - sdf_url
        properties:
          sdf_url:
            description: the url for the reference SDF to use
            type: string
            format: uri

      annotations:
        additionalProperties: false
        required:
          - mappability
        properties:
          mappability:
            additionalProperties: false
            required:
            - low
            - high
            properties:
              low:
                description: the url for low stringency mappability bed file
                type: string
                format: uri
              high:
                description: the url for high stringency mappability bed file
                type: string
                format: uri

################################################################################
# global

  global:
    anyOf:
      - $ref: "#/common/run_config"

################################################################################
# runs

  runs:
    patternProperties:
      ^[A-Za-z0-9_]+_v[0-9]+$:
        allOf:
          - $ref: "#/common/run_config"

################################################################################
# common

common:
  run_config:
    additionalProperties: false
    properties:
      features:
        additionalProperties: false
        patternProperties:
          ^[A-Za-z0-9_]+$:
            additionalProperties: false
            type: object
            properties:
              log_transform:
                description: log transform the feature if 'true'
                type: boolean
              fill_na:
                description: if present, fill missing values with this value
                type: number
      ebm:
        additionalProperties: false
        required:
          - test_size
        properties:
          test_size:
            description: |
              the size of the testing partition when training the model
            type: number
            minimum: 0
            maximum: 1
