$schema: "http://json-schema.org/draft-07/schema#"
description: explainable boosted machines pipeline
required:
  - paths
  - inputs
  - resources
  - ebm_runs
additionalProperties: false
properties:

################################################################################
# paths

  paths:
    additionalProperties: false
    required:
      - resources
      - results
    properties:
      resources:
        description: the path in which snakemake will put resource files
        type: string
      results:
        description: the path in which snakemake will put result files
        type: string

################################################################################
# inputs

  inputs:
    additionalProperties: false
    patternProperties:
      ^[\w\.\_]+$:
        required:
          - vcf
          - ref
          - benchmark
        additionalProperties: false
        properties:
          benchmark:
            description: the benchmark index to use for this input
            type: string

          ref:
            description: the reference index to use for this input
            type: string

          vcf:
            description: the vcf to use for this input
            type: string

          chr_filter:
            description: |
              A list of chromosomes filter when running all analyses. Empty
              list means include all chromosomes.
            type: array
            uniqueItems: true
            items:
              type: string
            default: []

################################################################################
# resources

  resources:
    additionalProperties: false
    required:
      - benchmarks
      - references
      - annotations
    properties:

      benchmarks:
        additionalProperties: false
        patternProperties:
          ^[\w\.\-]+$:
            additionalProperties: false
            required:
              - vcf_url
              - bed_url
              - tbi_url
            properties:
              vcf_url:
                description: the url for the benchmark VCF to use
                type: string
                format: uri
              tbi_url:
                description: the url for the benchmark VCF TBI to use
                type: string
                format: uri
              bed_url:
                description: the url for the benchmark bed to use
                type: string
                format: uri

      references:
        additionalProperties: false
        patternProperties:
          ^[\w\.\-]+$:
            required:
              - sdf
            additionalProperties: false
            properties:
              sdf:
                description: the url for the reference SDF to use
                type: string
                format: uri

      annotations:
        additionalProperties: false
        required:
          - mappability
          - superdups
          - homopolymers
        properties:
          mappability:
            additionalProperties: false
            required:
            - low
            - high
            properties:
              low:
                description: the url for low stringency mappability bed file
                type: string
                format: uri
              high:
                description: the url for high stringency mappability bed file
                type: string
                format: uri

          superdups:
            description: the url to the superdups txt file
            type: string
            format: uri

          homopolymers:
            required:
              - find_regions
              - fasta
            additionalProperties: false
            properties:
              find_regions:
                description: |
                  the url of the script to use when finding simple repeat regions
                type: string
                format: uri
              fasta:
                description: |
                  the url of the fasta file containing the simple regions
                type: string
                format: uri

################################################################################
# EBM runs

  ebm_runs:
    additionalProperties: false
    patternProperties:
      ^[\w_]+_v[0-9]+$:
        additionalProperties: false
        required:
          - inputs
          - filter
          - features
          - ebm_settings
        properties:
          inputs:
            description: |
              The input VCFs to use for this configuration as a list of lists.
              Each member in the outer list will be one EBM run, and each member
              in the inner list will be the keys for the VCF input results files
              to concat together row-wise where the input file will be denoted
              with the INPUT column in the final dataframe. Obviously is this
              sort of concatentation is not desired, the inner list is a
              singleton.
            type: array
            minItems: 1
            uniqueItems: true
            items:
              type: array
              minItems: 1
              uniqueItems: true
              items:
                type: string

          filter:
            description: |
              the filter(s) to use for this run as a list; either INDEL, SNP,
              or both
            type: array
            minItems: 1
            uniqueItems: true
            items:
              type: string
              pattern: ^INDEL|SNP$

          include_filtered:
            description: |
              If true, consider FILTER'ed entries in the query as positives
              (which in turn could be either TP or FP depending on if they are
              in the truth set). If false, FILTER'ed query entries are always
              consiered FN. Note that this only affects the way the training
              dataset for the EBMs is compiled. It does not affect the settings
              used for vcfeval (which is always run with 'all-records'), and
              thus the annotated dataframes will contain FP, FN, and TP
              depending on what is in the truth or query independent of FILTER.
            type: boolean
            default: true

          error_labels:
            description: |
              Labels in the annotated dataframe to consider as "errors" (which
              in the model will be the negative/0 class). The label "tp" will
              always mean "not error". By default, both "fn" and "fp" will
              be combined to mean "error". Any label that is not "tp" or listed
              in this parameter will be ignored.
            type: array
            minItems: 1
            uniqueItems: true
            items:
              type: string
              pattern: ^fn|fp$
            default: [fn, fp]

          features:
            additionalProperties: false
            patternProperties:
              ^[\w_]+$:
                additionalProperties: false
                type: object
                default: {}
                properties:
                  feature_type:
                    type: string
                    default: continuous
                    pattern: ^continuous|categorical$
                  log_transform:
                    description: log transform the feature if 'true'
                    type: boolean
                    default: false
                  fill_na:
                    description: if present, fill missing values with this value
                    type: number
                    default: 0

          interactions:
            description: |
              either a list of explicit interactions to use or an integer
              representing the number of interactions to use automatically
            default: 0
            anyOf:
              - type: number
                minimum: 0
              - type: array
                items:
                  type: array
                  minItems: 2
                  uniqueItems: true
                  items:
                    type: string
                    pattern: ^[\w\.\-]+$
                
          ebm_settings:
            additionalProperties: false
            properties:

              misc_parameters:
                description: |
                  random model parameters I don't know where else to put
                additionalProperties: false
                default: {}
                properties:
                  downsample:
                    default: null
                    anyOf:
                      - type: number
                        minimum: 0
                        maximum: 1
                      - type: "null"

              split_parameters:
                description: |
                  parameters for spliting the train/test data, will be sent to
                  'train_test_split' function
                additionalProperties: false
                default: {}
                properties:
                  test_size:
                    type: number
                    minimum: 0
                    maximum: 1
                    default: 0.2
    
                  random_state:
                    default: null
                    anyOf:
                      - type: number
                      - type: "null"

              # TODO where does mains belong?
              classifier_parameters:
                description: |
                  Parameters to train the EBM classifier, will be fed to
                  'ExplainableBoostingClassifier'. Note that 'feature_names',
                  'interactions', 'n_jobs', and 'mains' will be set elsewhere
                default: {}
                properties:
                  max_bins:
                    type: number
                    default: 256
    
                  max_interaction_bins:
                    type: number
                    default: 32
    
                  binning:
                    type: string
                    pattern: ^uniform|quantile|quantile_humanized$
                    default: quantile
    
                  outer_bags:
                    type: number
                    default: 8
    
                  inner_bags:
                    type: number
                    default: 0
    
                  learning_rate:
                    type: number
                    default: 0.01
    
                  validation_size:
                    type: number
                    default: 0.15
    
                  early_stopping_rounds:
                    type: number
                    default: 50
    
                  early_stopping_tolerance:
                    type: number
                    default: 0.0001
    
                  max_rounds:
                    type: number
                    default: 5000
    
                  min_samples_leaf:
                    type: number
                    default: 2
    
                  max_leaves:
                    type: number
                    default: 3
    
                  random_state:
                    default: null
                    anyOf:
                      - type: number
                      - type: "null"
