$schema: "http://json-schema.org/draft-07/schema#"
description: explainable boosted machines pipeline
required:
  - paths
  - inputs
  - resources
  - ebm_settings
  - feature_sets
  - ebm_runs
additionalProperties: false
properties:

################################################################################
# paths

  paths:
    additionalProperties: false
    required:
      - resources
      - results
    properties:
      resources:
        description: the path in which snakemake will put resource files
        type: string
      results:
        description: the path in which snakemake will put result files
        type: string

################################################################################
# inputs

  inputs:
    additionalProperties: false
    patternProperties:
      ^[\w\.\-]+$:
        required:
          - vcf
          - ref
          - benchmark
        additionalProperties: false
        properties:
          benchmark:
            description: the benchmark index to use for this input
            type: string

          ref:
            description: the reference index to use for this input
            type: string

          vcf:
            description: the vcf to use for this input
            type: string

################################################################################
# resources

  resources:
    additionalProperties: false
    required:
      - benchmarks
      - references
      - annotations
    properties:

      benchmarks:
        additionalProperties: false
        patternProperties:
          ^[\w\.\-]+$:
            additionalProperties: false
            required:
              - vcf_url
              - bed_url
              - tbi_url
            properties:
              vcf_url:
                description: the url for the benchmark VCF to use
                type: string
                format: uri
              tbi_url:
                description: the url for the benchmark VCF TBI to use
                type: string
                format: uri
              bed_url:
                description: the url for the benchmark bed to use
                type: string
                format: uri

      references:
        additionalProperties: false
        patternProperties:
          ^[\w\.\-]+$:
            required:
              - sdf
            additionalProperties: false
            properties:
              sdf:
                description: the url for the reference SDF to use
                type: string
                format: uri

      annotations:
        additionalProperties: false
        required:
          - mappability
        properties:
          mappability:
            additionalProperties: false
            required:
            - low
            - high
            properties:
              low:
                description: the url for low stringency mappability bed file
                type: string
                format: uri
              high:
                description: the url for high stringency mappability bed file
                type: string
                format: uri

################################################################################
# EBM settings

  ebm_settings:
    additionalProperties: false
    patternProperties:
      ^[\w\.\-]+$:
        properties:
          test_size:
            description: |
              the size of the testing partition when training the model
            type: number
            minimum: 0
            maximum: 1

################################################################################
# feature sets

  feature_sets:
    additionalProperties: false
    patternProperties:
      ^[\w\.\-]+$:
        additionalProperties: false
        patternProperties:
          ^[\w_]+$:
            additionalProperties: false
            properties:
              log_transform:
                description: log transform the feature if 'true'
                type: boolean
              fill_na:
                description: if present, fill missing values with this value
                type: number

################################################################################
# EBM runs

  ebm_runs:
    additionalProperties: false
    patternProperties:
      ^[\w_]+_v[0-9]+$:
        additionalProperties: false
        required:
          - input
          - filter
          - feature_set
        properties:
          input:
            description: the input index to use for this run
            type: string
          filter:
            description: the filter to use for this run; either INDEL or SNP
            type: string
            pattern: ^INDEL|SNP$
          feature_set: 
            description: the feature set to use for this run
            type: string
